local addonName, ns = ...

ns.Defaults = {
    profile = {
        Auras = {
            Blacklist = {
                [36032] = true,
            },
            ShowOnlyPlayer = false,
            UseLibCustomGlow = true,
            Whitelist = {
            },
        },
        Castbar = {
            boss1 = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 10,
                height = 10,
                iconScale = 1,
                point = "CENTER",
                relPoint = "BOTTOM",
                showIcon = false,
                width = 180,
                x = 0,
                y = 0,
            },
            boss2 = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 10,
                height = 10,
                iconScale = 1,
                point = "CENTER",
                relPoint = "BOTTOM",
                showIcon = false,
                width = 180,
                x = 0,
                y = 0,
            },
            boss3 = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 10,
                height = 10,
                iconScale = 1,
                point = "CENTER",
                relPoint = "BOTTOM",
                showIcon = false,
                width = 180,
                x = 0,
                y = 0,
            },
            boss4 = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 10,
                height = 10,
                iconScale = 1,
                point = "CENTER",
                relPoint = "BOTTOM",
                showIcon = false,
                width = 180,
                x = 0,
                y = 0,
            },
            boss5 = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 10,
                height = 10,
                iconScale = 1,
                point = "CENTER",
                relPoint = "BOTTOM",
                showIcon = false,
                width = 180,
                x = 0,
                y = 0,
            },
            colors_v4 = true,
            focus = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    interruptible = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = true,
                enabled = true,
                fontSize = 12,
                height = 20,
                iconScale = 1,
                point = "BOTTOM",
                relPoint = "CENTER",
                relativeTo = "FocusFrame",
                showIcon = false,
                width = 200,
                x = 503,
                y = 67.09,
            },
            focustarget = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = false,
                fontSize = 10,
                height = 15,
                iconScale = 1,
                point = "CENTER",
                relPoint = "CENTER",
                relativeTo = "FocusTargetFrame",
                showIcon = true,
                width = 120,
                x = 0,
                y = 0,
            },
            pet = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 10,
                height = 15,
                iconScale = 1,
                point = "CENTER",
                relPoint = "CENTER",
                relativeTo = "PetFrame",
                showIcon = false,
                width = 120,
                x = 0,
                y = 0,
            },
            player = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    failed = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                    success = {
                        [1] = 0,
                        [2] = 1,
                        [3] = 0,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 12,
                height = 20,
                icon = true,
                iconScale = 1,
                point = "CENTER",
                relPoint = "CENTER",
                showIcon = false,
                time = true,
                width = 235,
                x = 0,
                y = 0,
            },
            target = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    interruptible = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 12,
                height = 20,
                iconScale = 1,
                point = "CENTER",
                relPoint = "CENTER",
                relativeTo = "TargetFrame",
                showIcon = true,
                width = 200,
                x = 0,
                y = 0,
            },
            targettarget = {
                attached = false,
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = false,
                fontSize = 10,
                height = 15,
                iconScale = 1,
                point = "CENTER",
                relPoint = "CENTER",
                relativeTo = "TargetTargetFrame",
                showIcon = true,
                width = 120,
                x = 0,
                y = 0,
            },
        },
        Direction = {
            enabled = true,
            visibility = 1, -- 1:Always, 2:InCombat, 3:OutCombat, 4:Never
            left = {
                point = "CENTER",
                x = -200,
                y = 0,
                scale = 1,
            },
            right = {
                point = "CENTER",
                x = 200,
                y = 0,
                scale = 1,
            },
        },
        EnabledModules = {
            EncounterBar = true,
            FocusCastbar = true,
            FocusFrame = true,
            FocusTargetCastbar = true,
            PetCastbar = true,
            PetFrame = true,
            PlayerCastbar = true,
            PlayerFrame = true,
            TargetCastbar = true,
            TargetFrame = true,
            TargetTargetCastbar = true,
            TargetTargetFrame = true,
        },
        EncounterResource = {
            enabled = true,
            point = "TOP",
            x = 0,
            y = -100,
        },
        General = {
            Theme = "Class",
            castbarBar = "Solid",
            castbarFont = "Friz Quadrata TT",
            unitFrameBar = "Solid",
            unitFrameFont = "Friz Quadrata TT",
        },
        IndicatorTestMode = false,
        Range = {
            insideAlpha = 1,
            outsideAlpha = 0.4,
        },
        Theme = "ClassColors",
        Timers = {
            BattleRes = {
                enabled = true,
                point = "BOTTOM",
                scale = 1,
                x = -567.99978637695,
                y = 106.00060272217,
            },
            Bloodlust = {
                enabled = true,
                point = "TOP",
                scale = 1,
                x = 0,
                y = -100,
            },
        },
        UnitFrames = {
            BossGroup = {
                resetFix_V2 = true,
                x = 491.99896240234,
                y = 144.00022888184,
            },
            boss = {
                aurasEnabled = true,
                enabled = true,
                height = 40,
                indicators = {
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 20,
                        x = 0,
                        y = 5,
                    },
                },
                maxAuras = 4,
                point = "RIGHT",
                powerEnabled = true,
                powerHeight = 10,
                width = 180,
                x = -100,
                y = 100,
            },
            boss1 = {
                ShowOnlyPlayer = false,
                auraAnchor = "LEFT",
                auraGrowDirection = "LEFT",
                aurasEnabled = true,
                aurasSectionExpanded = false,
                enabled = true,
                height = 32,
                point = "CENTER",
                powerDetached = false,
                powerEnabled = true,
                powerHeight = 10,
                powerSectionExpanded = false,
                sizeSectionExpanded = true,
                spacing = 30,
                tags = {
                    [1] = {
                        anchorTo = "Frame",
                        enabled = true,
                        formatString = "@health.current:short - @health.percent",
                        order = 10,
                        point = "RIGHT",
                        x = 0,
                        y = 0,
                    },
                    [2] = {
                        anchorTo = "Power",
                        enabled = true,
                        formatString = "@power.percent",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                    [3] = {
                        anchorTo = "Frame",
                        enabled = true,
                        fontSize = 18,
                        formatString = "@name",
                        order = 10,
                        point = "TOPLEFT",
                        x = 0,
                        y = 10,
                    },
                },
                width = 170,
                x = 486.49932861328,
                y = 45.000762939453,
            },
            boss2 = {
                height = 50,
                point = "CENTER",
                width = 200,
                x = 406,
                y = 107,
            },
            boss3 = {
                height = 50,
                point = "CENTER",
                width = 200,
                x = 405,
                y = 173,
            },
            boss4 = {
                height = 50,
                point = "CENTER",
                width = 200,
                x = 404,
                y = 238,
            },
            boss5 = {
                height = 50,
                point = "TOP",
                powerDetached = false,
                powerEnabled = true,
                powerHeight = 10,
                powerWidth = 200,
                width = 200,
                x = 404,
                y = -209,
            },
            focus = {
                auraGrowDirection = "LEFT",
                aurasEnabled = true,
                enabled = true,
                height = 30,
                indicators = {
                    combat = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "BOTTOMLEFT",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    leader = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 8,
                    },
                    phase = {
                        enabled = true,
                        point = "CENTER",
                        size = 22,
                        x = 0,
                        y = 0,
                    },
                    pvp = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPRIGHT",
                        size = 24,
                        x = -10,
                        y = 10,
                    },
                    quest = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 20,
                        x = 10,
                        y = 10,
                    },
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 20,
                        x = 0,
                        y = 5,
                    },
                    readycheck = {
                        enabled = true,
                        point = "CENTER",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    resurrect = {
                        enabled = true,
                        point = "CENTER",
                        size = 24,
                        x = 0,
                        y = 0,
                    },
                    role = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 14,
                        y = 8,
                    },
                    tankassist = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 16,
                    },
                },
                maxAuras = 4,
                point = "BOTTOM",
                powerEnabled = true,
                powerHeight = 8,
                tags = {
                    [1] = {
                        anchorTo = "Frame",
                        enabled = true,
                        formatString = "@health.percent",
                        order = 10,
                        point = "RIGHT",
                        x = 0,
                        y = 0,
                    },
                    [2] = {
                        anchorTo = "Power",
                        enabled = true,
                        formatString = "@power.current",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                    [3] = {
                        anchorTo = "Frame",
                        enabled = true,
                        fontSize = 18,
                        formatString = "@name",
                        order = 10,
                        point = "TOPLEFT",
                        x = 0,
                        y = 11,
                    },
                },
                width = 200,
                x = 504,
                y = 12,
            },
            focustarget = {
                aurasEnabled = false,
                enabled = true,
                height = 30,
                indicators = {
                    combat = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "BOTTOMLEFT",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    leader = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 8,
                    },
                    phase = {
                        enabled = true,
                        point = "CENTER",
                        size = 22,
                        x = 0,
                        y = 0,
                    },
                    pvp = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPRIGHT",
                        size = 24,
                        x = -10,
                        y = 10,
                    },
                    quest = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 20,
                        x = 10,
                        y = 10,
                    },
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 20,
                        x = 0,
                        y = 5,
                    },
                    readycheck = {
                        enabled = true,
                        point = "CENTER",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    resurrect = {
                        enabled = true,
                        point = "CENTER",
                        size = 24,
                        x = 0,
                        y = 0,
                    },
                    role = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 14,
                        y = 8,
                    },
                    tankassist = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 16,
                    },
                },
                maxAuras = 8,
                point = "BOTTOMRIGHT",
                powerEnabled = true,
                powerSectionExpanded = true,
                tags = {
                    [1] = {
                        anchorTo = "Frame",
                        enabled = true,
                        formatString = "@health.percent",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                    [2] = {
                        anchorTo = "Power",
                        enabled = true,
                        formatString = "@power.current",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                },
                width = 120,
                x = -552,
                y = 12,
            },
            pet = {
                aurasEnabled = true,
                enabled = true,
                height = 30,
                indicators = {
                    combat = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "BOTTOMLEFT",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    leader = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 8,
                    },
                    phase = {
                        enabled = true,
                        point = "CENTER",
                        size = 22,
                        x = 0,
                        y = 0,
                    },
                    pvp = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPRIGHT",
                        size = 24,
                        x = -10,
                        y = 10,
                    },
                    quest = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 20,
                        x = 10,
                        y = 10,
                    },
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 20,
                        x = 0,
                        y = 5,
                    },
                    readycheck = {
                        enabled = true,
                        point = "CENTER",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    resurrect = {
                        enabled = true,
                        point = "CENTER",
                        size = 24,
                        x = 0,
                        y = 0,
                    },
                    role = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 14,
                        y = 8,
                    },
                    tankassist = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 16,
                    },
                },
                maxAuras = 8,
                point = "BOTTOM",
                powerDetached = false,
                powerEnabled = true,
                powerSectionExpanded = true,
                tags = {
                    [1] = {
                        anchorTo = "Frame",
                        enabled = true,
                        formatString = "@health.percent",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                },
                width = 120,
                x = -363,
                y = 34,
            },
            player = {
                ShowOnlyPlayer = false,
                additionalPowerDetached = false,
                additionalPowerEnabled = true,
                additionalPowerHeight = 10,
                additionalPowerPoint = "TOP",
                additionalPowerSectionExpanded = false,
                additionalPowerWidth = 230,
                additionalPowerX = 106.99920654297,
                additionalPowerY = -255.00018310547,
                auraAnchor = "TOP",
                auraGrowDirection = "LEFT",
                aurasEnabled = true,
                classPowerDetached = false,
                classPowerEnabled = true,
                classPowerHeight = 10,
                classPowerSectionExpanded = false,
                classPowerWidth = 230,
                enabled = true,
                healthTextFormat = "smart",
                height = 54,
                indicators = {
                    combat = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "BOTTOMLEFT",
                        size = 26,
                        x = 0,
                        y = 0,
                    },
                    leader = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 20,
                        x = 0,
                        y = 8,
                    },
                    phase = {
                        enabled = true,
                        point = "CENTER",
                        size = 59,
                        x = 0,
                        y = 0,
                    },
                    pvp = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPRIGHT",
                        size = 25,
                        x = -5,
                        y = 10,
                    },
                    quest = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 20,
                        x = 10,
                        y = 10,
                    },
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 30,
                        x = 0,
                        y = 5,
                    },
                    readycheck = {
                        enabled = true,
                        point = "CENTER",
                        size = 59,
                        x = 0,
                        y = 0,
                    },
                    resting = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 30,
                        x = 0,
                        y = 0,
                    },
                    resurrect = {
                        enabled = true,
                        point = "CENTER",
                        size = 55,
                        x = 0,
                        y = 0,
                    },
                    role = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 20,
                        x = 14,
                        y = 8,
                    },
                    tankassist = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 25,
                        x = 0,
                        y = 16,
                    },
                },
                maxAuras = 4,
                point = "CENTER",
                powerDetached = false,
                powerEnabled = true,
                powerHeight = 12,
                powerPoint = "CENTER",
                powerSectionExpanded = false,
                powerWidth = 230,
                powerX = -9,
                powerY = -13,
                showBuffs = false,
                tags = {
                    [1] = {
                        anchorTo = "Health",
                        enabled = true,
                        fontSize = 16,
                        formatString = "@health.current:short/@health.percent",
                        id = 1,
                        point = "RIGHT",
                        x = -5,
                        y = 0,
                    },
                    [2] = {
                        anchorTo = "Power",
                        enabled = true,
                        fontSize = 12,
                        formatString = "[mana](@power.percent) @power.current",
                        id = 2,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                    [3] = {
                        anchorTo = "Frame",
                        enabled = true,
                        formatString = "@absorb",
                        point = "BOTTOMLEFT",
                        x = 2,
                        y = 0,
                    },
                    [4] = {
                        anchorTo = "Frame",
                        enabled = true,
                        fontSize = 18,
                        formatString = "@name",
                        order = 10,
                        point = "TOPLEFT",
                        x = 0,
                        y = 12,
                    },
                },
                width = 238,
                x = -323,
                y = -132,
            },
            target = {
                auraAnchor = "TOP",
                auraGrowDirection = "LEFT",
                aurasEnabled = true,
                enabled = true,
                height = 50,
                indicators = {
                    combat = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "BOTTOMLEFT",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    leader = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 8,
                    },
                    phase = {
                        enabled = true,
                        point = "CENTER",
                        size = 22,
                        x = 0,
                        y = 0,
                    },
                    pvp = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPRIGHT",
                        size = 24,
                        x = -10,
                        y = 10,
                    },
                    quest = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 30,
                        x = 10,
                        y = 10,
                    },
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 20,
                        x = 0,
                        y = 5,
                    },
                    readycheck = {
                        enabled = true,
                        point = "CENTER",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    resurrect = {
                        enabled = true,
                        point = "CENTER",
                        size = 24,
                        x = 0,
                        y = 0,
                    },
                    role = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 14,
                        y = 8,
                    },
                    tankassist = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 16,
                    },
                },
                maxAuras = 4,
                point = "CENTER",
                powerDetached = false,
                powerEnabled = true,
                powerHeight = 12,
                powerSectionExpanded = false,
                tags = {
                    [1] = {
                        anchorTo = "Health",
                        enabled = true,
                        fontSize = 18,
                        formatString = "@name",
                        id = 1,
                        point = "TOPLEFT",
                        x = 5,
                        y = 12,
                    },
                    [2] = {
                        anchorTo = "Health",
                        enabled = true,
                        fontSize = 16,
                        formatString = "@health.current:short/@health.percent",
                        id = 2,
                        point = "RIGHT",
                        x = -5,
                        y = 0,
                    },
                    [3] = {
                        anchorTo = "Power",
                        enabled = true,
                        formatString = "[mana](@power.percent) @power.current",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                },
                width = 230,
                x = 316,
                y = -128,
            },
            targettarget = {
                aurasEnabled = false,
                enabled = true,
                height = 30,
                indicators = {
                    combat = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "BOTTOMLEFT",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    leader = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 8,
                    },
                    phase = {
                        enabled = true,
                        point = "CENTER",
                        size = 22,
                        x = 0,
                        y = 0,
                    },
                    pvp = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPRIGHT",
                        size = 24,
                        x = -10,
                        y = 10,
                    },
                    quest = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 20,
                        x = 10,
                        y = 10,
                    },
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 20,
                        x = 0,
                        y = 5,
                    },
                    readycheck = {
                        enabled = true,
                        point = "CENTER",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    resurrect = {
                        enabled = true,
                        point = "CENTER",
                        size = 24,
                        x = 0,
                        y = 0,
                    },
                    role = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 14,
                        y = 8,
                    },
                    tankassist = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 16,
                    },
                },
                maxAuras = 8,
                point = "CENTER",
                powerDetached = false,
                powerEnabled = true,
                powerSectionExpanded = false,
                tags = {
                    [1] = {
                        anchorTo = "Power",
                        enabled = true,
                        formatString = "[mana](@power.percent) @power.current",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                    [2] = {
                        anchorTo = "Frame",
                        enabled = true,
                        formatString = "@health.percent",
                        order = 10,
                        point = "RIGHT",
                        x = -5,
                        y = 0,
                    },
                    [3] = {
                        anchorTo = "Frame",
                        enabled = true,
                        fontSize = 10,
                        formatString = "@name",
                        order = 10,
                        point = "TOPLEFT",
                        x = 2,
                        y = 10,
                    },
                },
                width = 120,
                x = 500,
                y = -119,
            },
        },
        barTexture = "Solid",
        font = "Friz Quadrata TT",
        tempIndicatorSelect = "quest",
    }
}
