local addonName, ns = ...
if ns.skipLoad then return end

ns.Defaults = {
    profile = {
        Auras = {
            Blacklist = {
                [36032] = true,  -- Arcane Charges
                [57724] = true,  -- Sated (Bloodlust)
                [57723] = true,  -- Exhaustion (Heroism)
                [80354] = true,  -- Temporal Displacement (Time Warp)
                [95809] = true,  -- Insanity (Ancient Hysteria)
                [264689] = true, -- Fatigued (Primal Rage)
                [390435] = true, -- Allied Ether (Fury of the Aspects debuff)
            },
            ShowOnlyPlayer = false,
            UseLibCustomGlow = true,
            Whitelist = {
            },
            hideIcon = false,
            hideTimer = false,
            hideCount = false,
        },
        CustomAuraFrames = {},
        LEMDialogPosition = false,
        SmartFilters = {
            showAll = false,
            showCrowdControl = true,
            showMajorDefensives = true,
            showDispellable = true,
            showRaidBuffs = true,
            showImportant = true,
            showBossDebuffs = true,
        },
        Castbar = {
            boss1 = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 10,
                height = 10,
                iconScale = 1,
                point = "CENTER",
                relPoint = "BOTTOM",
                showIcon = false,
                width = 180,
                x = 0,
                y = 0,
            },
            boss2 = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 10,
                height = 10,
                iconScale = 1,
                point = "CENTER",
                relPoint = "BOTTOM",
                showIcon = false,
                width = 180,
                x = 0,
                y = 0,
            },
            boss3 = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 10,
                height = 10,
                iconScale = 1,
                point = "CENTER",
                relPoint = "BOTTOM",
                showIcon = false,
                width = 180,
                x = 0,
                y = 0,
            },
            boss4 = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 10,
                height = 10,
                iconScale = 1,
                point = "CENTER",
                relPoint = "BOTTOM",
                showIcon = false,
                width = 180,
                x = 0,
                y = 0,
            },
            boss5 = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 10,
                height = 10,
                iconScale = 1,
                point = "CENTER",
                relPoint = "BOTTOM",
                showIcon = false,
                width = 180,
                x = 0,
                y = 0,
            },
            colors_v4 = true,
            focus = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    interruptible = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = true,
                enabled = true,
                fontSize = 12,
                height = 20,
                iconScale = 1,
                point = "CENTER",
                relPoint = "CENTER",
                relativeTo = "UIParent",
                showIcon = false,
                width = 200,
                x = 250,
                y = 100,
            },
            focustarget = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = false,
                fontSize = 10,
                height = 15,
                iconScale = 1,
                point = "CENTER",
                relPoint = "CENTER",
                relativeTo = "FocusTargetFrame",
                showIcon = true,
                width = 120,
                x = 0,
                y = 0,
            },
            pet = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 10,
                height = 15,
                iconScale = 1,
                point = "CENTER",
                relPoint = "CENTER",
                relativeTo = "PetFrame",
                showIcon = false,
                width = 120,
                x = 0,
                y = 0,
            },
            player = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    failed = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                    success = {
                        [1] = 0,
                        [2] = 1,
                        [3] = 0,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 12,
                height = 20,
                icon = true,
                iconScale = 1,
                point = "CENTER",
                relPoint = "CENTER",
                showIcon = false,
                time = true,
                width = 235,
                x = 0,
                y = 0,
            },
            target = {
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    interruptible = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = true,
                fontSize = 12,
                height = 20,
                iconScale = 1,
                point = "CENTER",
                relPoint = "CENTER",
                relativeTo = "TargetFrame",
                showIcon = true,
                width = 200,
                x = 0,
                y = 0,
            },
            targettarget = {
                attached = false,
                colors = {
                    cast = {
                        [1] = 1,
                        [2] = 0.95,
                        [3] = 0,
                        [4] = 1,
                    },
                    channel = {
                        [1] = 0,
                        [2] = 0.98,
                        [3] = 1,
                        [4] = 1,
                    },
                    empower1 = {
                        [1] = 0.8,
                        [2] = 0.5,
                        [3] = 0.1,
                        [4] = 1,
                    },
                    empower2 = {
                        [1] = 0.9,
                        [2] = 0.9,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower3 = {
                        [1] = 0.2,
                        [2] = 0.7,
                        [3] = 0.2,
                        [4] = 1,
                    },
                    empower4 = {
                        [1] = 0.3,
                        [2] = 0.65,
                        [3] = 1,
                        [4] = 1,
                    },
                    interrupted = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    shield = {
                        [1] = 0.5,
                        [2] = 0.5,
                        [3] = 0.5,
                        [4] = 1,
                    },
                },
                detached = false,
                enabled = false,
                fontSize = 10,
                height = 15,
                iconScale = 1,
                point = "CENTER",
                relPoint = "CENTER",
                relativeTo = "TargetTargetFrame",
                showIcon = true,
                width = 120,
                x = 0,
                y = 0,
            },
        },

        EnabledModules = {
            UnitFrames = true,
            Castbar = true,
            EncounterBar = true,
            FocusCastbar = true,
            FocusFrame = true,
            FocusTargetCastbar = true,
            PetCastbar = true,
            PetFrame = true,
            PlayerCastbar = true,
            PlayerFrame = true,
            TargetCastbar = true,
            TargetFrame = true,
            TargetTargetCastbar = true,
            TargetTargetFrame = true,
            Minimap = true,
        },
        Minimap = {
            enabled = true,
            shape = "SQUARE",
            size = 200,
            width = 200,
            height = 200,
            scale = 1.0,
            borderSize = 1,
            borderColor = { r = 0.2, g = 0.2, b = 0.2, a = 1.0 },
            showZoom = false,
            showZoomIn = true,
            showZoomOut = true,
            showZoneText = true,
            showCalendar = false,
            showMail = true,
            showTracking = true,
            showLFG = true,
            showLanding = true,
            showDiel = true,
            zoneTextX = 0,
            zoneTextY = 0,
            showDataTextBar = true,
            dataTextPosition = "OUTSIDE",
            dataTextTimeFormat = "24H",
            dataTextTimeType = "LOCAL",
            dataTextBgColor = { r = 0.05, g = 0.05, b = 0.05, a = 0.6 },
            dataTextLeftType = "FPS",
            dataTextLeftFontSize = 11,
            dataTextLeftX = 0,
            dataTextLeftY = 0,
            dataTextMiddleType = "Time",
            dataTextMiddleFontSize = 11,
            dataTextMiddleX = 0,
            dataTextMiddleY = 0,
            dataTextRightType = "Social",
            dataTextRightFontSize = 11,
            dataTextRightX = 0,
            dataTextRightY = 0,
            showAddonBar = true,
            addonBarAttached = true,
            addonBarScale = 1.0,
            addonBarSnap = true,
            addonBarSnapEdge = "AUTO",
            addonBarExpanded = true,
            addonBarExpansionMode = "STANDARD",
            addonBarVisibleCount = 3,
            addonBarButtonSize = 30,
            addonBarExpanderSize = 16,
            addonBarSpacing = 4,
            addonBarColumns = 1,
            addonBarGrowDirection = "UP_LEFT",
            addonBarBreakpoint = 5,
            addonBarHide = false,
            addonBarAutohide = false,
            addonBarButtons = {},
            addonBarButtonOrder = {},
            addonBarBgColor = { r = 0, g = 0, b = 0, a = 0.6 },
            addonBarHoverColor = { r = 1, g = 1, b = 1, a = 1 },
            detached = {},
            offsets = {},
        },
        General = {
            Theme = "Class",
            castbarBar = "Solid",
            castbarFont = "Friz Quadrata TT",
            unitFrameBar = "Solid",
            unitFrameFont = "Friz Quadrata TT",
            debugMode = false,
        },
        IndicatorTestMode = false,
        Range = {
            insideAlpha = 1,
            outsideAlpha = 0.4,
        },
        Theme = "ClassColors",

        UnitFrames = {
            BossGroup = {
                resetFix_V2 = true,
                x = 491.99896240234,
                y = 144.00022888184,
            },
            boss = {
                aurasEnabled = true,
                enabled = true,
                height = 40,
                indicators = {
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 20,
                        x = 0,
                        y = 5,
                    },
                },
                maxAuras = 4,
                point = "RIGHT",
                powerEnabled = true,
                powerHeight = 10,
                width = 180,
                x = -100,
                y = 100,
            },
            boss1 = {
                ShowOnlyPlayer = false,
                auraAnchor = "TOPRIGHT",
                auraGrowDirection = "RIGHT_DOWN",
                aurasEnabled = true,
                auraDetached = false,
                auraSize = 30,
                aurasPerRow = 10,
                maxAuras = 10,
                auraX = 0,
                auraY = 0,
                aurasSectionExpanded = false,
                enabled = true,
                height = 32,
                point = "CENTER",
                powerDetached = false,
                powerEnabled = true,
                powerHeight = 10,
                powerSectionExpanded = false,
                sizeSectionExpanded = true,
                spacing = 30,
                tags = {
                    [1] = {
                        anchorTo = "Frame",
                        enabled = true,
                        formatString = "@health.current:short - @health.percent",
                        order = 10,
                        point = "RIGHT",
                        x = 0,
                        y = 0,
                    },
                    [2] = {
                        anchorTo = "Power",
                        enabled = true,
                        formatString = "@power.percent",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                    [3] = {
                        anchorTo = "Frame",
                        enabled = true,
                        fontSize = 18,
                        formatString = "@name",
                        order = 10,
                        point = "TOPLEFT",
                        x = 0,
                        y = 10,
                    },
                },
                width = 170,
                x = 486.49932861328,
                y = 45.000762939453,
            },
            boss2 = {
                auraAnchor = "TOPRIGHT",
                auraGrowDirection = "RIGHT_DOWN",
                aurasEnabled = true,
                auraDetached = false,
                auraSize = 30,
                aurasPerRow = 10,
                maxAuras = 10,
                auraX = 0,
                auraY = 0,
                height = 50,
                point = "CENTER",
                width = 200,
                x = 406,
                y = 107,
            },
            boss3 = {
                auraAnchor = "TOPRIGHT",
                auraGrowDirection = "RIGHT_DOWN",
                aurasEnabled = true,
                auraDetached = false,
                auraSize = 30,
                aurasPerRow = 10,
                maxAuras = 10,
                auraX = 0,
                auraY = 0,
                height = 50,
                point = "CENTER",
                width = 200,
                x = 405,
                y = 173,
            },
            boss4 = {
                auraAnchor = "TOPRIGHT",
                auraGrowDirection = "RIGHT_DOWN",
                aurasEnabled = true,
                auraDetached = false,
                auraSize = 30,
                aurasPerRow = 10,
                maxAuras = 10,
                auraX = 0,
                auraY = 0,
                height = 50,
                point = "CENTER",
                width = 200,
                x = 404,
                y = 238,
            },
            boss5 = {
                auraAnchor = "TOPRIGHT",
                auraGrowDirection = "RIGHT_DOWN",
                aurasEnabled = true,
                auraDetached = false,
                auraSize = 30,
                aurasPerRow = 10,
                maxAuras = 10,
                auraX = 0,
                auraY = 0,
                height = 50,
                point = "TOP",
                powerDetached = false,
                powerEnabled = true,
                powerHeight = 10,
                powerWidth = 200,
                width = 200,
                x = 404,
                y = -209,
            },
            focus = {
                auraGrowDirection = "LEFT",
                aurasEnabled = true,
                enabled = true,
                height = 30,
                indicators = {
                    combat = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "BOTTOMLEFT",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    leader = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 8,
                    },
                    phase = {
                        enabled = true,
                        point = "CENTER",
                        size = 22,
                        x = 0,
                        y = 0,
                    },
                    pvp = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPRIGHT",
                        size = 24,
                        x = -10,
                        y = 10,
                    },
                    quest = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 20,
                        x = 10,
                        y = 10,
                    },
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 20,
                        x = 0,
                        y = 5,
                    },
                    readycheck = {
                        enabled = true,
                        point = "CENTER",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    resurrect = {
                        enabled = true,
                        point = "CENTER",
                        size = 24,
                        x = 0,
                        y = 0,
                    },
                    role = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 14,
                        y = 8,
                    },
                    tankassist = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 16,
                    },
                },
                maxAuras = 4,
                point = "BOTTOM",
                powerEnabled = true,
                powerHeight = 8,
                tags = {
                    [1] = {
                        anchorTo = "Frame",
                        enabled = true,
                        formatString = "@health.percent",
                        order = 10,
                        point = "RIGHT",
                        x = 0,
                        y = 0,
                    },
                    [2] = {
                        anchorTo = "Power",
                        enabled = true,
                        formatString = "@power.current",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                    [3] = {
                        anchorTo = "Frame",
                        enabled = true,
                        fontSize = 18,
                        formatString = "@name",
                        order = 10,
                        point = "TOPLEFT",
                        x = 0,
                        y = 11,
                    },
                },
                width = 200,
                x = 504,
                y = 12,
            },
            focustarget = {
                aurasEnabled = false,
                enabled = true,
                height = 30,
                indicators = {
                    combat = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "BOTTOMLEFT",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    leader = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 8,
                    },
                    phase = {
                        enabled = true,
                        point = "CENTER",
                        size = 22,
                        x = 0,
                        y = 0,
                    },
                    pvp = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPRIGHT",
                        size = 24,
                        x = -10,
                        y = 10,
                    },
                    quest = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 20,
                        x = 10,
                        y = 10,
                    },
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 20,
                        x = 0,
                        y = 5,
                    },
                    readycheck = {
                        enabled = true,
                        point = "CENTER",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    resurrect = {
                        enabled = true,
                        point = "CENTER",
                        size = 24,
                        x = 0,
                        y = 0,
                    },
                    role = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 14,
                        y = 8,
                    },
                    tankassist = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 16,
                    },
                },
                maxAuras = 8,
                point = "BOTTOMRIGHT",
                powerEnabled = true,
                powerSectionExpanded = true,
                tags = {
                    [1] = {
                        anchorTo = "Frame",
                        enabled = true,
                        formatString = "@health.percent",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                    [2] = {
                        anchorTo = "Power",
                        enabled = true,
                        formatString = "@power.current",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                },
                width = 120,
                x = -552,
                y = 12,
            },
            pet = {
                aurasEnabled = true,
                enabled = true,
                height = 30,
                indicators = {
                    combat = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "BOTTOMLEFT",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    leader = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 8,
                    },
                    phase = {
                        enabled = true,
                        point = "CENTER",
                        size = 22,
                        x = 0,
                        y = 0,
                    },
                    pvp = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPRIGHT",
                        size = 24,
                        x = -10,
                        y = 10,
                    },
                    quest = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 20,
                        x = 10,
                        y = 10,
                    },
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 20,
                        x = 0,
                        y = 5,
                    },
                    readycheck = {
                        enabled = true,
                        point = "CENTER",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    resurrect = {
                        enabled = true,
                        point = "CENTER",
                        size = 24,
                        x = 0,
                        y = 0,
                    },
                    role = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 14,
                        y = 8,
                    },
                    tankassist = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 16,
                    },
                },
                maxAuras = 8,
                point = "BOTTOM",
                powerDetached = false,
                powerEnabled = true,
                powerSectionExpanded = true,
                tags = {
                    [1] = {
                        anchorTo = "Frame",
                        enabled = true,
                        formatString = "@health.percent",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                },
                width = 120,
                x = -363,
                y = 34,
            },
            player = {
                ShowOnlyPlayer = false,
                additionalPowerDetached = false,
                additionalPowerEnabled = true,
                additionalPowerHeight = 10,
                additionalPowerPoint = "TOP",
                additionalPowerSectionExpanded = false,
                additionalPowerWidth = 230,
                additionalPowerX = 106.99920654297,
                additionalPowerY = -255.00018310547,
                auraAnchor = "BOTTOM",
                auraGrowDirection = "RIGHT_DOWN",
                aurasEnabled = true,
                separateAuras = true,
                showBuffs = false,
                showDebuffs = true,
                hideTimeless = true,
                hideIcon = false,
                hideTimer = false,
                hideCount = false,
                showAllBuffs = false,
                playerBuffs = false,
                raidInCombat = false,
                importantBuffs = false,
                majorDefensivesBuffs = false,
                majorDefensives = false,
                externalDefensives = false,
                onlyWhitelistBuffs = false,
                additionalWhitelistBuffs = false,
                showAllDebuffs = false,
                playerDebuffs = false,
                importantDebuffs = true,
                crowdControl = false,
                cc = false,
                dispellable = true,
                onlyDispellable = true,
                majorDefensivesDebuffs = false,
                onlyWhitelistDebuffs = false,
                additionalWhitelistDebuffs = false,
                debuffSize = 20,
                debuffMaxAuras = 4,
                maxDebuffs = 4,
                debuffsPerRow = 8,
                debuffSpacing = 4,
                debuffAnchor = "BOTTOMRIGHT",
                debuffGrowDirection = "LEFT_DOWN",
                debuffDetached = false,
                debuffXOffset = 0,
                debuffX = 0,
                debuffYOffset = 4,
                debuffY = 4,
                zoomPercent = 15,
                timerFontSize = 10,
                timerAnchor = "CENTER",
                timerX = 0,
                timerY = 0,
                stackFontSize = 10,
                stackAnchor = "TOP",
                stackX = 0,
                stackY = 6,
                classPowerDetached = false,
                classPowerEnabled = true,
                classPowerHeight = 10,
                classPowerSectionExpanded = false,
                classPowerWidth = 230,
                enabled = true,
                healthTextFormat = "smart",
                height = 54,
                indicators = {
                    combat = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "BOTTOMLEFT",
                        size = 26,
                        x = 0,
                        y = 0,
                    },
                    leader = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 20,
                        x = 0,
                        y = 8,
                    },
                    phase = {
                        enabled = true,
                        point = "CENTER",
                        size = 59,
                        x = 0,
                        y = 0,
                    },
                    pvp = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPRIGHT",
                        size = 25,
                        x = -5,
                        y = 10,
                    },
                    quest = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 20,
                        x = 10,
                        y = 10,
                    },
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 30,
                        x = 0,
                        y = 5,
                    },
                    readycheck = {
                        enabled = true,
                        point = "CENTER",
                        size = 59,
                        x = 0,
                        y = 0,
                    },
                    resting = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 30,
                        x = 0,
                        y = 0,
                    },
                    resurrect = {
                        enabled = true,
                        point = "CENTER",
                        size = 55,
                        x = 0,
                        y = 0,
                    },
                    role = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 20,
                        x = 14,
                        y = 8,
                    },
                    tankassist = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 25,
                        x = 0,
                        y = 16,
                    },
                },
                maxAuras = 4,
                point = "CENTER",
                powerDetached = false,
                powerEnabled = true,
                powerHeight = 12,
                powerPoint = "CENTER",
                powerSectionExpanded = false,
                powerWidth = 230,
                powerX = -9,
                powerY = -13,
                tags = {
                    [1] = {
                        anchorTo = "Health",
                        enabled = true,
                        fontSize = 16,
                        formatString = "@health.current:short/@health.percent",
                        id = 1,
                        point = "RIGHT",
                        x = -5,
                        y = 0,
                    },
                    [2] = {
                        anchorTo = "Power",
                        enabled = true,
                        fontSize = 12,
                        formatString = "[mana](@power.percent) @power.current",
                        id = 2,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                    [3] = {
                        anchorTo = "Frame",
                        enabled = true,
                        formatString = "@absorb",
                        point = "BOTTOMLEFT",
                        x = 2,
                        y = 0,
                    },
                    [4] = {
                        anchorTo = "Frame",
                        enabled = true,
                        fontSize = 18,
                        formatString = "@name",
                        order = 10,
                        point = "TOPLEFT",
                        x = 0,
                        y = 12,
                    },
                },
                width = 238,
                x = -323,
                y = -132,
            },
            target = {
                auraAnchor = "TOP",
                auraGrowDirection = "LEFT",
                aurasEnabled = true,
                separateAuras = true,
                showBuffs = true,
                showDebuffs = true,
                buffSize = 20,
                buffMaxAuras = 8,
                maxBuffs = 8,
                buffsPerRow = 8,
                buffSpacing = 1,
                buffAnchor = "TOPRIGHT",
                buffGrowDirection = "LEFT_UP",
                buffDetached = false,
                buffXOffset = 0,
                buffX = 0,
                buffYOffset = 0,
                buffY = 0,
                debuffSize = 20,
                debuffMaxAuras = 8,
                maxDebuffs = 8,
                debuffsPerRow = 8,
                debuffSpacing = 1,
                debuffAnchor = "BOTTOMLEFT",
                debuffGrowDirection = "RIGHT_UP",
                debuffDetached = false,
                debuffXOffset = 0,
                debuffX = 0,
                debuffYOffset = 0,
                debuffY = 0,
                zoomPercent = 15,
                timerFontSize = 10,
                timerAnchor = "CENTER",
                timerX = 0,
                timerY = 0,
                stackFontSize = 10,
                stackAnchor = "TOP",
                stackX = 0,
                stackY = 6,
                enabled = true,
                height = 50,
                indicators = {
                    combat = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "BOTTOMLEFT",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    leader = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 8,
                    },
                    phase = {
                        enabled = true,
                        point = "CENTER",
                        size = 22,
                        x = 0,
                        y = 0,
                    },
                    pvp = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPRIGHT",
                        size = 24,
                        x = -10,
                        y = 10,
                    },
                    quest = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 30,
                        x = 10,
                        y = 10,
                    },
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 20,
                        x = 0,
                        y = 5,
                    },
                    readycheck = {
                        enabled = true,
                        point = "CENTER",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    resurrect = {
                        enabled = true,
                        point = "CENTER",
                        size = 24,
                        x = 0,
                        y = 0,
                    },
                    role = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 14,
                        y = 8,
                    },
                    tankassist = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 16,
                    },
                },
                maxAuras = 8,
                point = "CENTER",
                powerDetached = false,
                powerEnabled = true,
                powerHeight = 12,
                powerSectionExpanded = false,
                tags = {
                    [1] = {
                        anchorTo = "Health",
                        enabled = true,
                        fontSize = 18,
                        formatString = "@name",
                        id = 1,
                        point = "TOPLEFT",
                        x = 5,
                        y = 12,
                    },
                    [2] = {
                        anchorTo = "Health",
                        enabled = true,
                        fontSize = 16,
                        formatString = "@health.current:short/@health.percent",
                        id = 2,
                        point = "RIGHT",
                        x = -5,
                        y = 0,
                    },
                    [3] = {
                        anchorTo = "Power",
                        enabled = true,
                        formatString = "[mana](@power.percent) @power.current",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                },
                width = 230,
                x = 316,
                y = -128,
            },
            targettarget = {
                aurasEnabled = false,
                enabled = true,
                height = 30,
                indicators = {
                    combat = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "BOTTOMLEFT",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    leader = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 8,
                    },
                    phase = {
                        enabled = true,
                        point = "CENTER",
                        size = 22,
                        x = 0,
                        y = 0,
                    },
                    pvp = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPRIGHT",
                        size = 24,
                        x = -10,
                        y = 10,
                    },
                    quest = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOPLEFT",
                        size = 20,
                        x = 10,
                        y = 10,
                    },
                    raidicon = {
                        enabled = true,
                        point = "CENTER",
                        relativePoint = "TOP",
                        size = 20,
                        x = 0,
                        y = 5,
                    },
                    readycheck = {
                        enabled = true,
                        point = "CENTER",
                        size = 20,
                        x = 0,
                        y = 0,
                    },
                    resurrect = {
                        enabled = true,
                        point = "CENTER",
                        size = 24,
                        x = 0,
                        y = 0,
                    },
                    role = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 14,
                        y = 8,
                    },
                    tankassist = {
                        enabled = true,
                        point = "TOPLEFT",
                        size = 16,
                        x = 0,
                        y = 16,
                    },
                },
                maxAuras = 8,
                point = "CENTER",
                powerDetached = false,
                powerEnabled = true,
                powerSectionExpanded = false,
                tags = {
                    [1] = {
                        anchorTo = "Power",
                        enabled = true,
                        formatString = "[mana](@power.percent) @power.current",
                        order = 10,
                        point = "CENTER",
                        x = 0,
                        y = 0,
                    },
                    [2] = {
                        anchorTo = "Frame",
                        enabled = true,
                        formatString = "@health.percent",
                        order = 10,
                        point = "RIGHT",
                        x = -5,
                        y = 0,
                    },
                    [3] = {
                        anchorTo = "Frame",
                        enabled = true,
                        fontSize = 10,
                        formatString = "@name",
                        order = 10,
                        point = "TOPLEFT",
                        x = 2,
                        y = 10,
                    },
                },
                width = 120,
                x = 500,
                y = -119,
            },
        },
        barTexture = "Solid",
        font = "Friz Quadrata TT",
        tempIndicatorSelect = "quest",
        CooldownManager = {
            enabled = true,
            cropIcons = true,
            centerIncompleteRows = true,
            borderSize = 1,
            borderColor = { r = 0.2, g = 0.2, b = 0.2, a = 1.0 },
            font = "Friz Quadrata TT",
            cooldownFontSize = 14,
            cooldownFontOutline = "OUTLINE",
            stackAnchor = "BOTTOMRIGHT",
            stackOffsetX = -2,
            stackOffsetY = 2,
            stackFontSize = 11,
            stackFontOutline = "OUTLINE",
            viewers = {
                Essential = {
                    enabled = true,
                    iconSize = 50,
                    spacing = 4,
                    growthDirection = "RIGHT",
                    align = "CENTER",
                },
                Utility = {
                    enabled = true,
                    iconSize = 32,
                    spacing = 4,
                    growthDirection = "RIGHT",
                    align = "CENTER",
                },
                BuffIcon = {
                    enabled = true,
                    iconSize = 40,
                    spacing = 4,
                    growthDirection = "RIGHT",
                    align = "CENTER",
                },
                BuffBar = {
                    enabled = true,
                    barWidth = 220,
                    barHeight = 24,
                    spacing = 4,
                    growthDirection = "DOWN",
                },
            },
        },
        Actionbars = {
            enabled = true,
            showHotkeys = true,
            showMacroText = true,
            showCount = true,
            iconZoom = 0.07,
            font = "Friz Quadrata TT",
            fontSize = 11,
            borderColor = { r = 0.2, g = 0.2, b = 0.2, a = 1.0 },
            bar1 = { enabled = true, buttonSize = 36, spacing = 4, buttonsPerRow = 12, maxButtons = 12, orientation = "HORIZONTAL", point = "BOTTOM", x = 0, y = 30, alpha = 1.0, mouseover = false, mouseoverAlpha = 0, hideEmpty = false },
            bar2 = { enabled = true, buttonSize = 36, spacing = 4, buttonsPerRow = 12, maxButtons = 12, orientation = "HORIZONTAL", point = "BOTTOM", x = 0, y = 70, alpha = 1.0, mouseover = false, mouseoverAlpha = 0, hideEmpty = false },
            bar3 = { enabled = true, buttonSize = 36, spacing = 4, buttonsPerRow = 12, maxButtons = 12, orientation = "HORIZONTAL", point = "BOTTOM", x = 0, y = 110, alpha = 1.0, mouseover = false, mouseoverAlpha = 0, hideEmpty = false },
            bar4 = { enabled = true, buttonSize = 36, spacing = 4, buttonsPerRow = 12, maxButtons = 12, orientation = "HORIZONTAL", point = "BOTTOM", x = 0, y = 150, alpha = 1.0, mouseover = false, mouseoverAlpha = 0, hideEmpty = false },
            bar5 = { enabled = true, buttonSize = 36, spacing = 4, buttonsPerRow = 12, maxButtons = 12, orientation = "HORIZONTAL", point = "BOTTOM", x = 0, y = 190, alpha = 1.0, mouseover = false, mouseoverAlpha = 0, hideEmpty = false },
            bar6 = { enabled = false, buttonSize = 36, spacing = 4, buttonsPerRow = 12, maxButtons = 12, orientation = "HORIZONTAL", point = "BOTTOM", x = 0, y = 230, alpha = 1.0, mouseover = false, mouseoverAlpha = 0, hideEmpty = false },
            bar7 = { enabled = false, buttonSize = 36, spacing = 4, buttonsPerRow = 12, maxButtons = 12, orientation = "HORIZONTAL", point = "BOTTOM", x = 0, y = 270, alpha = 1.0, mouseover = false, mouseoverAlpha = 0, hideEmpty = false },
            bar8 = { enabled = false, buttonSize = 36, spacing = 4, buttonsPerRow = 12, maxButtons = 12, orientation = "HORIZONTAL", point = "BOTTOM", x = 0, y = 310, alpha = 1.0, mouseover = false, mouseoverAlpha = 0, hideEmpty = false },
            pet = { enabled = true, buttonSize = 30, spacing = 4, buttonsPerRow = 10, maxButtons = 10, orientation = "HORIZONTAL", point = "BOTTOM", x = 0, y = 230, alpha = 1.0, mouseover = false, mouseoverAlpha = 0, hideEmpty = false },
            stance = { enabled = true, buttonSize = 30, spacing = 4, buttonsPerRow = 10, maxButtons = 10, orientation = "HORIZONTAL", point = "BOTTOM", x = 0, y = 265, alpha = 1.0, mouseover = false, mouseoverAlpha = 0, hideEmpty = false },
            extraAction = { enabled = true, buttonSize = 52, maxButtons = 1, point = "CENTER", x = 0, y = -100, alpha = 1.0 },
            zoneAction = { enabled = true, buttonSize = 52, maxButtons = 1, point = "CENTER", x = 0, y = -160, alpha = 1.0 },
        },
        Bags = {
            enabled = true,
            slotSize = 36,
            spacing = 4,
            columns = 10,
            showItemLevel = true,
            qualityBorders = true,
            showEmptySlots = true,
            autoSellJunk = false,
            favorites = {},
            customFilters = {},
            customCategoryAssignments = {},
            activeCategory = "ALL",
            bagBar = {
                enabled = true,
                expanded = false,
                buttonSize = 30,
                spacing = 4,
                point = "BOTTOMLEFT",
                x = 10,
                y = 285,
            },
            bagWindow = {
                point = "BOTTOMRIGHT",
                x = -10,
                y = 80,
            },
        },
        Totems = {
            enabled = true,
            orientation = "HORIZONTAL",
            buttonSize = 36,
            spacing = 4,
            fontSize = 11,
            showKeybind = true,
            showDuration = true,
            showCooldown = true,
            showEarth = true,
            showFire = true,
            showWater = true,
            showAir = true,
            showShield = true,
            showWeapon = true,
            point = "BOTTOM",
            x = 0,
            y = 150,
            disabledSpells = {},
            selectedSpells = {},
        },
        Menu = {
            enabled = true,
            styleMicroMenu = true,
            showBackground = false,
            backgroundColor = { r = 0.05, g = 0.05, b = 0.05, a = 0.85 },
            borderColor = { r = 0.2, g = 0.2, b = 0.2, a = 1.0 },
            buttonWidth = 24,
            buttonHeight = 32,
            spacing = 2,
            orientation = "HORIZONTAL",
            alpha = 1.0,
            mouseover = false,
            mouseoverAlpha = 0.0,
            point = "BOTTOMLEFT",
            x = 10,
            y = 285,
        },
        SwingTimer = {
            enabled = true,
            player = {
                enabled = true,
                width = 200,
                height = 12,
                showOffhand = true,
                showText = true,
                point = "CENTER",
                x = 0,
                y = -140,
                colorMain = { r = 1.0, g = 0.82, b = 0.0, a = 1.0 },
                colorOff = { r = 0.35, g = 0.75, b = 1.0, a = 1.0 },
                colorRanged = { r = 0.2, g = 0.85, b = 0.35, a = 1.0 },
            },
            target = {
                enabled = true,
                width = 200,
                height = 12,
                showText = true,
                point = "CENTER",
                x = 0,
                y = -160,
                color = { r = 0.85, g = 0.25, b = 0.25, a = 1.0 },
            },
        },
        Chat = {
            enabled = true,
            showBackground = true,
            backgroundColor = { r = 0.03, g = 0.045, b = 0.05, a = 0.65 },
            showBorder = true,
            borderColor = { r = 0.15, g = 0.15, b = 0.15, a = 1.0 },
            borderSize = 1,
            font = "Interface\\AddOns\\RoithiUI\\Media\\Fonts\\Expressway.ttf",
            fontSize = 12,
            fontOutline = "OUTLINE",
            editBoxHeight = 24,
            editBoxPosition = "BOTTOM",
            editBoxBgColor = { r = 0.05, g = 0.065, b = 0.08, a = 0.9 },
            editBoxBorderColor = { r = 0.2, g = 0.2, b = 0.2, a = 1.0 },
            hideBlizzardChrome = true,
            styleTabs = true,
            tabHeight = 22,
            tabFontSize = 11,
            tabAlphaInactive = 0.5,
            tabAlphaActive = 1.0,
        },
        Objectives = {
            enabled = true,
            font = "Interface\\AddOns\\RoithiUI\\Media\\Fonts\\Expressway.ttf",
            fontOutline = "OUTLINE",
            headerFontSize = 13,
            titleFontSize = 12,
            objectiveFontSize = 11,
            headerColor = { r = 0.05, g = 0.82, b = 0.61, a = 1.0 },
            titleColor = { r = 1.0, g = 0.85, b = 0.35, a = 1.0 },
            objectiveColor = { r = 0.8, g = 0.8, b = 0.8, a = 1.0 },
            completedColor = { r = 0.25, g = 1.0, b = 0.35, a = 1.0 },
            showAccentDivider = true,
            skinProgressBars = true,
            hideMasterHeader = false,
            point = "TOPRIGHT",
            x = -50,
            y = -200,
        },
    }
}
